from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from brp.historie_api.models.base_model import Model
from brp.historie_api import util


class AbstractVerblijfplaatsVoorkomen(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None):  # noqa: E501
        """AbstractVerblijfplaatsVoorkomen - a model defined in OpenAPI

        :param type: The type of this AbstractVerblijfplaatsVoorkomen.  # noqa: E501
        :type type: str
        """
        self.openapi_types = {
            'type': str
        }

        self.attribute_map = {
            'type': 'type'
        }

        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'AbstractVerblijfplaatsVoorkomen':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AbstractVerblijfplaatsVoorkomen of this AbstractVerblijfplaatsVoorkomen.  # noqa: E501
        :rtype: AbstractVerblijfplaatsVoorkomen
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this AbstractVerblijfplaatsVoorkomen.


        :return: The type of this AbstractVerblijfplaatsVoorkomen.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this AbstractVerblijfplaatsVoorkomen.


        :param type: The type of this AbstractVerblijfplaatsVoorkomen.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type
