from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from brp.historie_api.models.base_model import Model
from brp.historie_api.models.abstract_datum import AbstractDatum
from brp.historie_api.models.abstract_verblijfplaats_voorkomen import AbstractVerblijfplaatsVoorkomen
from brp.historie_api.models.adres_voorkomen_in_onderzoek import AdresVoorkomenInOnderzoek
from brp.historie_api.models.adressering_binnenland import AdresseringBinnenland
from brp.historie_api.models.verblijfadres_binnenland import VerblijfadresBinnenland
from brp.historie_api.models.waardetabel import Waardetabel
import re
from brp.historie_api import util

from brp.historie_api.models.abstract_datum import AbstractDatum  # noqa: E501
from brp.historie_api.models.abstract_verblijfplaats_voorkomen import AbstractVerblijfplaatsVoorkomen  # noqa: E501
from brp.historie_api.models.adres_voorkomen_in_onderzoek import AdresVoorkomenInOnderzoek  # noqa: E501
from brp.historie_api.models.adressering_binnenland import AdresseringBinnenland  # noqa: E501
from brp.historie_api.models.verblijfadres_binnenland import VerblijfadresBinnenland  # noqa: E501
from brp.historie_api.models.waardetabel import Waardetabel  # noqa: E501
import re  # noqa: E501

class AdresVoorkomen(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, verblijfadres=None, functie_adres=None, adresseerbaar_object_identificatie=None, nummeraanduiding_identificatie=None, gemeente_van_inschrijving=None, datum_van=None, datum_tot=None, verblijft_niet_op_adres_vanaf=None, in_onderzoek=None, adressering=None):  # noqa: E501
        """AdresVoorkomen - a model defined in OpenAPI

        :param type: The type of this AdresVoorkomen.  # noqa: E501
        :type type: str
        :param verblijfadres: The verblijfadres of this AdresVoorkomen.  # noqa: E501
        :type verblijfadres: VerblijfadresBinnenland
        :param functie_adres: The functie_adres of this AdresVoorkomen.  # noqa: E501
        :type functie_adres: Waardetabel
        :param adresseerbaar_object_identificatie: The adresseerbaar_object_identificatie of this AdresVoorkomen.  # noqa: E501
        :type adresseerbaar_object_identificatie: str
        :param nummeraanduiding_identificatie: The nummeraanduiding_identificatie of this AdresVoorkomen.  # noqa: E501
        :type nummeraanduiding_identificatie: str
        :param gemeente_van_inschrijving: The gemeente_van_inschrijving of this AdresVoorkomen.  # noqa: E501
        :type gemeente_van_inschrijving: Waardetabel
        :param datum_van: The datum_van of this AdresVoorkomen.  # noqa: E501
        :type datum_van: AbstractDatum
        :param datum_tot: The datum_tot of this AdresVoorkomen.  # noqa: E501
        :type datum_tot: AbstractDatum
        :param verblijft_niet_op_adres_vanaf: The verblijft_niet_op_adres_vanaf of this AdresVoorkomen.  # noqa: E501
        :type verblijft_niet_op_adres_vanaf: AbstractDatum
        :param in_onderzoek: The in_onderzoek of this AdresVoorkomen.  # noqa: E501
        :type in_onderzoek: AdresVoorkomenInOnderzoek
        :param adressering: The adressering of this AdresVoorkomen.  # noqa: E501
        :type adressering: AdresseringBinnenland
        """
        self.openapi_types = {
            'type': str,
            'verblijfadres': VerblijfadresBinnenland,
            'functie_adres': Waardetabel,
            'adresseerbaar_object_identificatie': str,
            'nummeraanduiding_identificatie': str,
            'gemeente_van_inschrijving': Waardetabel,
            'datum_van': AbstractDatum,
            'datum_tot': AbstractDatum,
            'verblijft_niet_op_adres_vanaf': AbstractDatum,
            'in_onderzoek': AdresVoorkomenInOnderzoek,
            'adressering': AdresseringBinnenland
        }

        self.attribute_map = {
            'type': 'type',
            'verblijfadres': 'verblijfadres',
            'functie_adres': 'functieAdres',
            'adresseerbaar_object_identificatie': 'adresseerbaarObjectIdentificatie',
            'nummeraanduiding_identificatie': 'nummeraanduidingIdentificatie',
            'gemeente_van_inschrijving': 'gemeenteVanInschrijving',
            'datum_van': 'datumVan',
            'datum_tot': 'datumTot',
            'verblijft_niet_op_adres_vanaf': 'verblijftNietOpAdresVanaf',
            'in_onderzoek': 'inOnderzoek',
            'adressering': 'adressering'
        }

        self._type = type
        self._verblijfadres = verblijfadres
        self._functie_adres = functie_adres
        self._adresseerbaar_object_identificatie = adresseerbaar_object_identificatie
        self._nummeraanduiding_identificatie = nummeraanduiding_identificatie
        self._gemeente_van_inschrijving = gemeente_van_inschrijving
        self._datum_van = datum_van
        self._datum_tot = datum_tot
        self._verblijft_niet_op_adres_vanaf = verblijft_niet_op_adres_vanaf
        self._in_onderzoek = in_onderzoek
        self._adressering = adressering

    @classmethod
    def from_dict(cls, dikt) -> 'AdresVoorkomen':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AdresVoorkomen of this AdresVoorkomen.  # noqa: E501
        :rtype: AdresVoorkomen
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this AdresVoorkomen.


        :return: The type of this AdresVoorkomen.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this AdresVoorkomen.


        :param type: The type of this AdresVoorkomen.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def verblijfadres(self) -> VerblijfadresBinnenland:
        """Gets the verblijfadres of this AdresVoorkomen.


        :return: The verblijfadres of this AdresVoorkomen.
        :rtype: VerblijfadresBinnenland
        """
        return self._verblijfadres

    @verblijfadres.setter
    def verblijfadres(self, verblijfadres: VerblijfadresBinnenland):
        """Sets the verblijfadres of this AdresVoorkomen.


        :param verblijfadres: The verblijfadres of this AdresVoorkomen.
        :type verblijfadres: VerblijfadresBinnenland
        """

        self._verblijfadres = verblijfadres

    @property
    def functie_adres(self) -> Waardetabel:
        """Gets the functie_adres of this AdresVoorkomen.


        :return: The functie_adres of this AdresVoorkomen.
        :rtype: Waardetabel
        """
        return self._functie_adres

    @functie_adres.setter
    def functie_adres(self, functie_adres: Waardetabel):
        """Sets the functie_adres of this AdresVoorkomen.


        :param functie_adres: The functie_adres of this AdresVoorkomen.
        :type functie_adres: Waardetabel
        """

        self._functie_adres = functie_adres

    @property
    def adresseerbaar_object_identificatie(self) -> str:
        """Gets the adresseerbaar_object_identificatie of this AdresVoorkomen.

        De verblijfplaats van de persoon kan een ligplaats, een standplaats of een verblijfsobject zijn.   # noqa: E501

        :return: The adresseerbaar_object_identificatie of this AdresVoorkomen.
        :rtype: str
        """
        return self._adresseerbaar_object_identificatie

    @adresseerbaar_object_identificatie.setter
    def adresseerbaar_object_identificatie(self, adresseerbaar_object_identificatie: str):
        """Sets the adresseerbaar_object_identificatie of this AdresVoorkomen.

        De verblijfplaats van de persoon kan een ligplaats, een standplaats of een verblijfsobject zijn.   # noqa: E501

        :param adresseerbaar_object_identificatie: The adresseerbaar_object_identificatie of this AdresVoorkomen.
        :type adresseerbaar_object_identificatie: str
        """
        if adresseerbaar_object_identificatie is not None and not re.search(r'^[0-9]{16}$', adresseerbaar_object_identificatie):  # noqa: E501
            raise ValueError(r"Invalid value for `adresseerbaar_object_identificatie`, must be a follow pattern or equal to `/^[0-9]{16}$/`")  # noqa: E501

        self._adresseerbaar_object_identificatie = adresseerbaar_object_identificatie

    @property
    def nummeraanduiding_identificatie(self) -> str:
        """Gets the nummeraanduiding_identificatie of this AdresVoorkomen.

        Unieke identificatie van een nummeraanduiding (en het bijbehorende adres) in de BAG.   # noqa: E501

        :return: The nummeraanduiding_identificatie of this AdresVoorkomen.
        :rtype: str
        """
        return self._nummeraanduiding_identificatie

    @nummeraanduiding_identificatie.setter
    def nummeraanduiding_identificatie(self, nummeraanduiding_identificatie: str):
        """Sets the nummeraanduiding_identificatie of this AdresVoorkomen.

        Unieke identificatie van een nummeraanduiding (en het bijbehorende adres) in de BAG.   # noqa: E501

        :param nummeraanduiding_identificatie: The nummeraanduiding_identificatie of this AdresVoorkomen.
        :type nummeraanduiding_identificatie: str
        """
        if nummeraanduiding_identificatie is not None and not re.search(r'^[0-9]{16}$', nummeraanduiding_identificatie):  # noqa: E501
            raise ValueError(r"Invalid value for `nummeraanduiding_identificatie`, must be a follow pattern or equal to `/^[0-9]{16}$/`")  # noqa: E501

        self._nummeraanduiding_identificatie = nummeraanduiding_identificatie

    @property
    def gemeente_van_inschrijving(self) -> Waardetabel:
        """Gets the gemeente_van_inschrijving of this AdresVoorkomen.


        :return: The gemeente_van_inschrijving of this AdresVoorkomen.
        :rtype: Waardetabel
        """
        return self._gemeente_van_inschrijving

    @gemeente_van_inschrijving.setter
    def gemeente_van_inschrijving(self, gemeente_van_inschrijving: Waardetabel):
        """Sets the gemeente_van_inschrijving of this AdresVoorkomen.


        :param gemeente_van_inschrijving: The gemeente_van_inschrijving of this AdresVoorkomen.
        :type gemeente_van_inschrijving: Waardetabel
        """

        self._gemeente_van_inschrijving = gemeente_van_inschrijving

    @property
    def datum_van(self) -> AbstractDatum:
        """Gets the datum_van of this AdresVoorkomen.


        :return: The datum_van of this AdresVoorkomen.
        :rtype: AbstractDatum
        """
        return self._datum_van

    @datum_van.setter
    def datum_van(self, datum_van: AbstractDatum):
        """Sets the datum_van of this AdresVoorkomen.


        :param datum_van: The datum_van of this AdresVoorkomen.
        :type datum_van: AbstractDatum
        """

        self._datum_van = datum_van

    @property
    def datum_tot(self) -> AbstractDatum:
        """Gets the datum_tot of this AdresVoorkomen.


        :return: The datum_tot of this AdresVoorkomen.
        :rtype: AbstractDatum
        """
        return self._datum_tot

    @datum_tot.setter
    def datum_tot(self, datum_tot: AbstractDatum):
        """Sets the datum_tot of this AdresVoorkomen.


        :param datum_tot: The datum_tot of this AdresVoorkomen.
        :type datum_tot: AbstractDatum
        """

        self._datum_tot = datum_tot

    @property
    def verblijft_niet_op_adres_vanaf(self) -> AbstractDatum:
        """Gets the verblijft_niet_op_adres_vanaf of this AdresVoorkomen.


        :return: The verblijft_niet_op_adres_vanaf of this AdresVoorkomen.
        :rtype: AbstractDatum
        """
        return self._verblijft_niet_op_adres_vanaf

    @verblijft_niet_op_adres_vanaf.setter
    def verblijft_niet_op_adres_vanaf(self, verblijft_niet_op_adres_vanaf: AbstractDatum):
        """Sets the verblijft_niet_op_adres_vanaf of this AdresVoorkomen.


        :param verblijft_niet_op_adres_vanaf: The verblijft_niet_op_adres_vanaf of this AdresVoorkomen.
        :type verblijft_niet_op_adres_vanaf: AbstractDatum
        """

        self._verblijft_niet_op_adres_vanaf = verblijft_niet_op_adres_vanaf

    @property
    def in_onderzoek(self) -> AdresVoorkomenInOnderzoek:
        """Gets the in_onderzoek of this AdresVoorkomen.


        :return: The in_onderzoek of this AdresVoorkomen.
        :rtype: AdresVoorkomenInOnderzoek
        """
        return self._in_onderzoek

    @in_onderzoek.setter
    def in_onderzoek(self, in_onderzoek: AdresVoorkomenInOnderzoek):
        """Sets the in_onderzoek of this AdresVoorkomen.


        :param in_onderzoek: The in_onderzoek of this AdresVoorkomen.
        :type in_onderzoek: AdresVoorkomenInOnderzoek
        """

        self._in_onderzoek = in_onderzoek

    @property
    def adressering(self) -> AdresseringBinnenland:
        """Gets the adressering of this AdresVoorkomen.


        :return: The adressering of this AdresVoorkomen.
        :rtype: AdresseringBinnenland
        """
        return self._adressering

    @adressering.setter
    def adressering(self, adressering: AdresseringBinnenland):
        """Sets the adressering of this AdresVoorkomen.


        :param adressering: The adressering of this AdresVoorkomen.
        :type adressering: AdresseringBinnenland
        """

        self._adressering = adressering
