from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from brp.historie_api.models.base_model import Model
from brp.historie_api.models.abstract_datum import AbstractDatum
from brp.historie_api import util

from brp.historie_api.models.abstract_datum import AbstractDatum  # noqa: E501

class AdresseringBuitenlandInOnderzoek(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum_ingang_onderzoek=None, adresregel1=None, adresregel2=None, adresregel3=None, land=None):  # noqa: E501
        """AdresseringBuitenlandInOnderzoek - a model defined in OpenAPI

        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this AdresseringBuitenlandInOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek: AbstractDatum
        :param adresregel1: The adresregel1 of this AdresseringBuitenlandInOnderzoek.  # noqa: E501
        :type adresregel1: bool
        :param adresregel2: The adresregel2 of this AdresseringBuitenlandInOnderzoek.  # noqa: E501
        :type adresregel2: bool
        :param adresregel3: The adresregel3 of this AdresseringBuitenlandInOnderzoek.  # noqa: E501
        :type adresregel3: bool
        :param land: The land of this AdresseringBuitenlandInOnderzoek.  # noqa: E501
        :type land: bool
        """
        self.openapi_types = {
            'datum_ingang_onderzoek': AbstractDatum,
            'adresregel1': bool,
            'adresregel2': bool,
            'adresregel3': bool,
            'land': bool
        }

        self.attribute_map = {
            'datum_ingang_onderzoek': 'datumIngangOnderzoek',
            'adresregel1': 'adresregel1',
            'adresregel2': 'adresregel2',
            'adresregel3': 'adresregel3',
            'land': 'land'
        }

        self._datum_ingang_onderzoek = datum_ingang_onderzoek
        self._adresregel1 = adresregel1
        self._adresregel2 = adresregel2
        self._adresregel3 = adresregel3
        self._land = land

    @classmethod
    def from_dict(cls, dikt) -> 'AdresseringBuitenlandInOnderzoek':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AdresseringBuitenlandInOnderzoek of this AdresseringBuitenlandInOnderzoek.  # noqa: E501
        :rtype: AdresseringBuitenlandInOnderzoek
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum_ingang_onderzoek(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek of this AdresseringBuitenlandInOnderzoek.


        :return: The datum_ingang_onderzoek of this AdresseringBuitenlandInOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek

    @datum_ingang_onderzoek.setter
    def datum_ingang_onderzoek(self, datum_ingang_onderzoek: AbstractDatum):
        """Sets the datum_ingang_onderzoek of this AdresseringBuitenlandInOnderzoek.


        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this AdresseringBuitenlandInOnderzoek.
        :type datum_ingang_onderzoek: AbstractDatum
        """

        self._datum_ingang_onderzoek = datum_ingang_onderzoek

    @property
    def adresregel1(self) -> bool:
        """Gets the adresregel1 of this AdresseringBuitenlandInOnderzoek.


        :return: The adresregel1 of this AdresseringBuitenlandInOnderzoek.
        :rtype: bool
        """
        return self._adresregel1

    @adresregel1.setter
    def adresregel1(self, adresregel1: bool):
        """Sets the adresregel1 of this AdresseringBuitenlandInOnderzoek.


        :param adresregel1: The adresregel1 of this AdresseringBuitenlandInOnderzoek.
        :type adresregel1: bool
        """

        self._adresregel1 = adresregel1

    @property
    def adresregel2(self) -> bool:
        """Gets the adresregel2 of this AdresseringBuitenlandInOnderzoek.


        :return: The adresregel2 of this AdresseringBuitenlandInOnderzoek.
        :rtype: bool
        """
        return self._adresregel2

    @adresregel2.setter
    def adresregel2(self, adresregel2: bool):
        """Sets the adresregel2 of this AdresseringBuitenlandInOnderzoek.


        :param adresregel2: The adresregel2 of this AdresseringBuitenlandInOnderzoek.
        :type adresregel2: bool
        """

        self._adresregel2 = adresregel2

    @property
    def adresregel3(self) -> bool:
        """Gets the adresregel3 of this AdresseringBuitenlandInOnderzoek.


        :return: The adresregel3 of this AdresseringBuitenlandInOnderzoek.
        :rtype: bool
        """
        return self._adresregel3

    @adresregel3.setter
    def adresregel3(self, adresregel3: bool):
        """Sets the adresregel3 of this AdresseringBuitenlandInOnderzoek.


        :param adresregel3: The adresregel3 of this AdresseringBuitenlandInOnderzoek.
        :type adresregel3: bool
        """

        self._adresregel3 = adresregel3

    @property
    def land(self) -> bool:
        """Gets the land of this AdresseringBuitenlandInOnderzoek.


        :return: The land of this AdresseringBuitenlandInOnderzoek.
        :rtype: bool
        """
        return self._land

    @land.setter
    def land(self, land: bool):
        """Sets the land of this AdresseringBuitenlandInOnderzoek.


        :param land: The land of this AdresseringBuitenlandInOnderzoek.
        :type land: bool
        """

        self._land = land
