from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from brp.historie_api.models.base_model import Model
from brp.historie_api.models.adressering_buitenland_in_onderzoek import AdresseringBuitenlandInOnderzoek
from brp.historie_api.models.waardetabel import Waardetabel
from brp.historie_api import util

from brp.historie_api.models.adressering_buitenland_in_onderzoek import AdresseringBuitenlandInOnderzoek  # noqa: E501
from brp.historie_api.models.waardetabel import Waardetabel  # noqa: E501

class AdresseringBuitenland(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, adresregel1=None, adresregel2=None, adresregel3=None, land=None, in_onderzoek=None):  # noqa: E501
        """AdresseringBuitenland - a model defined in OpenAPI

        :param adresregel1: The adresregel1 of this AdresseringBuitenland.  # noqa: E501
        :type adresregel1: str
        :param adresregel2: The adresregel2 of this AdresseringBuitenland.  # noqa: E501
        :type adresregel2: str
        :param adresregel3: The adresregel3 of this AdresseringBuitenland.  # noqa: E501
        :type adresregel3: str
        :param land: The land of this AdresseringBuitenland.  # noqa: E501
        :type land: Waardetabel
        :param in_onderzoek: The in_onderzoek of this AdresseringBuitenland.  # noqa: E501
        :type in_onderzoek: AdresseringBuitenlandInOnderzoek
        """
        self.openapi_types = {
            'adresregel1': str,
            'adresregel2': str,
            'adresregel3': str,
            'land': Waardetabel,
            'in_onderzoek': AdresseringBuitenlandInOnderzoek
        }

        self.attribute_map = {
            'adresregel1': 'adresregel1',
            'adresregel2': 'adresregel2',
            'adresregel3': 'adresregel3',
            'land': 'land',
            'in_onderzoek': 'inOnderzoek'
        }

        self._adresregel1 = adresregel1
        self._adresregel2 = adresregel2
        self._adresregel3 = adresregel3
        self._land = land
        self._in_onderzoek = in_onderzoek

    @classmethod
    def from_dict(cls, dikt) -> 'AdresseringBuitenland':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AdresseringBuitenland of this AdresseringBuitenland.  # noqa: E501
        :rtype: AdresseringBuitenland
        """
        return util.deserialize_model(dikt, cls)

    @property
    def adresregel1(self) -> str:
        """Gets the adresregel1 of this AdresseringBuitenland.

        Het eerste deel van een adres is een combinatie van de straat en huisnummer.   # noqa: E501

        :return: The adresregel1 of this AdresseringBuitenland.
        :rtype: str
        """
        return self._adresregel1

    @adresregel1.setter
    def adresregel1(self, adresregel1: str):
        """Sets the adresregel1 of this AdresseringBuitenland.

        Het eerste deel van een adres is een combinatie van de straat en huisnummer.   # noqa: E501

        :param adresregel1: The adresregel1 of this AdresseringBuitenland.
        :type adresregel1: str
        """
        if adresregel1 is not None and len(adresregel1) > 40:
            raise ValueError("Invalid value for `adresregel1`, length must be less than or equal to `40`")  # noqa: E501

        self._adresregel1 = adresregel1

    @property
    def adresregel2(self) -> str:
        """Gets the adresregel2 of this AdresseringBuitenland.

        Het tweede deel van een adres is een combinatie van woonplaats eventueel in combinatie met de postcode.   # noqa: E501

        :return: The adresregel2 of this AdresseringBuitenland.
        :rtype: str
        """
        return self._adresregel2

    @adresregel2.setter
    def adresregel2(self, adresregel2: str):
        """Sets the adresregel2 of this AdresseringBuitenland.

        Het tweede deel van een adres is een combinatie van woonplaats eventueel in combinatie met de postcode.   # noqa: E501

        :param adresregel2: The adresregel2 of this AdresseringBuitenland.
        :type adresregel2: str
        """
        if adresregel2 is not None and len(adresregel2) > 50:
            raise ValueError("Invalid value for `adresregel2`, length must be less than or equal to `50`")  # noqa: E501

        self._adresregel2 = adresregel2

    @property
    def adresregel3(self) -> str:
        """Gets the adresregel3 of this AdresseringBuitenland.

        Het derde deel van een adres is optioneel. Het gaat om een of meer geografische gebieden van het adres in het buitenland.   # noqa: E501

        :return: The adresregel3 of this AdresseringBuitenland.
        :rtype: str
        """
        return self._adresregel3

    @adresregel3.setter
    def adresregel3(self, adresregel3: str):
        """Sets the adresregel3 of this AdresseringBuitenland.

        Het derde deel van een adres is optioneel. Het gaat om een of meer geografische gebieden van het adres in het buitenland.   # noqa: E501

        :param adresregel3: The adresregel3 of this AdresseringBuitenland.
        :type adresregel3: str
        """
        if adresregel3 is not None and len(adresregel3) > 35:
            raise ValueError("Invalid value for `adresregel3`, length must be less than or equal to `35`")  # noqa: E501

        self._adresregel3 = adresregel3

    @property
    def land(self) -> Waardetabel:
        """Gets the land of this AdresseringBuitenland.


        :return: The land of this AdresseringBuitenland.
        :rtype: Waardetabel
        """
        return self._land

    @land.setter
    def land(self, land: Waardetabel):
        """Sets the land of this AdresseringBuitenland.


        :param land: The land of this AdresseringBuitenland.
        :type land: Waardetabel
        """

        self._land = land

    @property
    def in_onderzoek(self) -> AdresseringBuitenlandInOnderzoek:
        """Gets the in_onderzoek of this AdresseringBuitenland.


        :return: The in_onderzoek of this AdresseringBuitenland.
        :rtype: AdresseringBuitenlandInOnderzoek
        """
        return self._in_onderzoek

    @in_onderzoek.setter
    def in_onderzoek(self, in_onderzoek: AdresseringBuitenlandInOnderzoek):
        """Sets the in_onderzoek of this AdresseringBuitenland.


        :param in_onderzoek: The in_onderzoek of this AdresseringBuitenland.
        :type in_onderzoek: AdresseringBuitenlandInOnderzoek
        """

        self._in_onderzoek = in_onderzoek
