from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from brp.historie_api.models.base_model import Model
from brp.historie_api.models.adressering_binnenland_in_onderzoek import AdresseringBinnenlandInOnderzoek
from brp.historie_api import util

from brp.historie_api.models.adressering_binnenland_in_onderzoek import AdresseringBinnenlandInOnderzoek  # noqa: E501

class AdresseringBinnenland(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, adresregel1=None, adresregel2=None, in_onderzoek=None):  # noqa: E501
        """AdresseringBinnenland - a model defined in OpenAPI

        :param adresregel1: The adresregel1 of this AdresseringBinnenland.  # noqa: E501
        :type adresregel1: str
        :param adresregel2: The adresregel2 of this AdresseringBinnenland.  # noqa: E501
        :type adresregel2: str
        :param in_onderzoek: The in_onderzoek of this AdresseringBinnenland.  # noqa: E501
        :type in_onderzoek: AdresseringBinnenlandInOnderzoek
        """
        self.openapi_types = {
            'adresregel1': str,
            'adresregel2': str,
            'in_onderzoek': AdresseringBinnenlandInOnderzoek
        }

        self.attribute_map = {
            'adresregel1': 'adresregel1',
            'adresregel2': 'adresregel2',
            'in_onderzoek': 'inOnderzoek'
        }

        self._adresregel1 = adresregel1
        self._adresregel2 = adresregel2
        self._in_onderzoek = in_onderzoek

    @classmethod
    def from_dict(cls, dikt) -> 'AdresseringBinnenland':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AdresseringBinnenland of this AdresseringBinnenland.  # noqa: E501
        :rtype: AdresseringBinnenland
        """
        return util.deserialize_model(dikt, cls)

    @property
    def adresregel1(self) -> str:
        """Gets the adresregel1 of this AdresseringBinnenland.

        Het eerste deel van een adres is een combinatie van de straat en huisnummer.   # noqa: E501

        :return: The adresregel1 of this AdresseringBinnenland.
        :rtype: str
        """
        return self._adresregel1

    @adresregel1.setter
    def adresregel1(self, adresregel1: str):
        """Sets the adresregel1 of this AdresseringBinnenland.

        Het eerste deel van een adres is een combinatie van de straat en huisnummer.   # noqa: E501

        :param adresregel1: The adresregel1 of this AdresseringBinnenland.
        :type adresregel1: str
        """
        if adresregel1 is not None and len(adresregel1) > 40:
            raise ValueError("Invalid value for `adresregel1`, length must be less than or equal to `40`")  # noqa: E501

        self._adresregel1 = adresregel1

    @property
    def adresregel2(self) -> str:
        """Gets the adresregel2 of this AdresseringBinnenland.

        Het tweede deel van een adres is een combinatie van woonplaats eventueel in combinatie met de postcode.   # noqa: E501

        :return: The adresregel2 of this AdresseringBinnenland.
        :rtype: str
        """
        return self._adresregel2

    @adresregel2.setter
    def adresregel2(self, adresregel2: str):
        """Sets the adresregel2 of this AdresseringBinnenland.

        Het tweede deel van een adres is een combinatie van woonplaats eventueel in combinatie met de postcode.   # noqa: E501

        :param adresregel2: The adresregel2 of this AdresseringBinnenland.
        :type adresregel2: str
        """
        if adresregel2 is not None and len(adresregel2) > 50:
            raise ValueError("Invalid value for `adresregel2`, length must be less than or equal to `50`")  # noqa: E501

        self._adresregel2 = adresregel2

    @property
    def in_onderzoek(self) -> AdresseringBinnenlandInOnderzoek:
        """Gets the in_onderzoek of this AdresseringBinnenland.


        :return: The in_onderzoek of this AdresseringBinnenland.
        :rtype: AdresseringBinnenlandInOnderzoek
        """
        return self._in_onderzoek

    @in_onderzoek.setter
    def in_onderzoek(self, in_onderzoek: AdresseringBinnenlandInOnderzoek):
        """Sets the in_onderzoek of this AdresseringBinnenland.


        :param in_onderzoek: The in_onderzoek of this AdresseringBinnenland.
        :type in_onderzoek: AdresseringBinnenlandInOnderzoek
        """

        self._in_onderzoek = in_onderzoek
