from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from brp.historie_api.models.base_model import Model
from brp.historie_api.models.abstract_datum import AbstractDatum
from brp.historie_api import util

from brp.historie_api.models.abstract_datum import AbstractDatum  # noqa: E501

class AdresVoorkomenInOnderzoek(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum_ingang_onderzoek=None, type=None, gemeente_van_inschrijving=None, datum_van=None, datum_tot=None, nummeraanduiding_identificatie=None, adresseerbaar_object_identificatie=None, functie_adres=None):  # noqa: E501
        """AdresVoorkomenInOnderzoek - a model defined in OpenAPI

        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this AdresVoorkomenInOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek: AbstractDatum
        :param type: The type of this AdresVoorkomenInOnderzoek.  # noqa: E501
        :type type: bool
        :param gemeente_van_inschrijving: The gemeente_van_inschrijving of this AdresVoorkomenInOnderzoek.  # noqa: E501
        :type gemeente_van_inschrijving: bool
        :param datum_van: The datum_van of this AdresVoorkomenInOnderzoek.  # noqa: E501
        :type datum_van: bool
        :param datum_tot: The datum_tot of this AdresVoorkomenInOnderzoek.  # noqa: E501
        :type datum_tot: bool
        :param nummeraanduiding_identificatie: The nummeraanduiding_identificatie of this AdresVoorkomenInOnderzoek.  # noqa: E501
        :type nummeraanduiding_identificatie: bool
        :param adresseerbaar_object_identificatie: The adresseerbaar_object_identificatie of this AdresVoorkomenInOnderzoek.  # noqa: E501
        :type adresseerbaar_object_identificatie: bool
        :param functie_adres: The functie_adres of this AdresVoorkomenInOnderzoek.  # noqa: E501
        :type functie_adres: bool
        """
        self.openapi_types = {
            'datum_ingang_onderzoek': AbstractDatum,
            'type': bool,
            'gemeente_van_inschrijving': bool,
            'datum_van': bool,
            'datum_tot': bool,
            'nummeraanduiding_identificatie': bool,
            'adresseerbaar_object_identificatie': bool,
            'functie_adres': bool
        }

        self.attribute_map = {
            'datum_ingang_onderzoek': 'datumIngangOnderzoek',
            'type': 'type',
            'gemeente_van_inschrijving': 'gemeenteVanInschrijving',
            'datum_van': 'datumVan',
            'datum_tot': 'datumTot',
            'nummeraanduiding_identificatie': 'nummeraanduidingIdentificatie',
            'adresseerbaar_object_identificatie': 'adresseerbaarObjectIdentificatie',
            'functie_adres': 'functieAdres'
        }

        self._datum_ingang_onderzoek = datum_ingang_onderzoek
        self._type = type
        self._gemeente_van_inschrijving = gemeente_van_inschrijving
        self._datum_van = datum_van
        self._datum_tot = datum_tot
        self._nummeraanduiding_identificatie = nummeraanduiding_identificatie
        self._adresseerbaar_object_identificatie = adresseerbaar_object_identificatie
        self._functie_adres = functie_adres

    @classmethod
    def from_dict(cls, dikt) -> 'AdresVoorkomenInOnderzoek':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AdresVoorkomenInOnderzoek of this AdresVoorkomenInOnderzoek.  # noqa: E501
        :rtype: AdresVoorkomenInOnderzoek
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum_ingang_onderzoek(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek of this AdresVoorkomenInOnderzoek.


        :return: The datum_ingang_onderzoek of this AdresVoorkomenInOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek

    @datum_ingang_onderzoek.setter
    def datum_ingang_onderzoek(self, datum_ingang_onderzoek: AbstractDatum):
        """Sets the datum_ingang_onderzoek of this AdresVoorkomenInOnderzoek.


        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this AdresVoorkomenInOnderzoek.
        :type datum_ingang_onderzoek: AbstractDatum
        """

        self._datum_ingang_onderzoek = datum_ingang_onderzoek

    @property
    def type(self) -> bool:
        """Gets the type of this AdresVoorkomenInOnderzoek.


        :return: The type of this AdresVoorkomenInOnderzoek.
        :rtype: bool
        """
        return self._type

    @type.setter
    def type(self, type: bool):
        """Sets the type of this AdresVoorkomenInOnderzoek.


        :param type: The type of this AdresVoorkomenInOnderzoek.
        :type type: bool
        """

        self._type = type

    @property
    def gemeente_van_inschrijving(self) -> bool:
        """Gets the gemeente_van_inschrijving of this AdresVoorkomenInOnderzoek.


        :return: The gemeente_van_inschrijving of this AdresVoorkomenInOnderzoek.
        :rtype: bool
        """
        return self._gemeente_van_inschrijving

    @gemeente_van_inschrijving.setter
    def gemeente_van_inschrijving(self, gemeente_van_inschrijving: bool):
        """Sets the gemeente_van_inschrijving of this AdresVoorkomenInOnderzoek.


        :param gemeente_van_inschrijving: The gemeente_van_inschrijving of this AdresVoorkomenInOnderzoek.
        :type gemeente_van_inschrijving: bool
        """

        self._gemeente_van_inschrijving = gemeente_van_inschrijving

    @property
    def datum_van(self) -> bool:
        """Gets the datum_van of this AdresVoorkomenInOnderzoek.


        :return: The datum_van of this AdresVoorkomenInOnderzoek.
        :rtype: bool
        """
        return self._datum_van

    @datum_van.setter
    def datum_van(self, datum_van: bool):
        """Sets the datum_van of this AdresVoorkomenInOnderzoek.


        :param datum_van: The datum_van of this AdresVoorkomenInOnderzoek.
        :type datum_van: bool
        """

        self._datum_van = datum_van

    @property
    def datum_tot(self) -> bool:
        """Gets the datum_tot of this AdresVoorkomenInOnderzoek.


        :return: The datum_tot of this AdresVoorkomenInOnderzoek.
        :rtype: bool
        """
        return self._datum_tot

    @datum_tot.setter
    def datum_tot(self, datum_tot: bool):
        """Sets the datum_tot of this AdresVoorkomenInOnderzoek.


        :param datum_tot: The datum_tot of this AdresVoorkomenInOnderzoek.
        :type datum_tot: bool
        """

        self._datum_tot = datum_tot

    @property
    def nummeraanduiding_identificatie(self) -> bool:
        """Gets the nummeraanduiding_identificatie of this AdresVoorkomenInOnderzoek.


        :return: The nummeraanduiding_identificatie of this AdresVoorkomenInOnderzoek.
        :rtype: bool
        """
        return self._nummeraanduiding_identificatie

    @nummeraanduiding_identificatie.setter
    def nummeraanduiding_identificatie(self, nummeraanduiding_identificatie: bool):
        """Sets the nummeraanduiding_identificatie of this AdresVoorkomenInOnderzoek.


        :param nummeraanduiding_identificatie: The nummeraanduiding_identificatie of this AdresVoorkomenInOnderzoek.
        :type nummeraanduiding_identificatie: bool
        """

        self._nummeraanduiding_identificatie = nummeraanduiding_identificatie

    @property
    def adresseerbaar_object_identificatie(self) -> bool:
        """Gets the adresseerbaar_object_identificatie of this AdresVoorkomenInOnderzoek.


        :return: The adresseerbaar_object_identificatie of this AdresVoorkomenInOnderzoek.
        :rtype: bool
        """
        return self._adresseerbaar_object_identificatie

    @adresseerbaar_object_identificatie.setter
    def adresseerbaar_object_identificatie(self, adresseerbaar_object_identificatie: bool):
        """Sets the adresseerbaar_object_identificatie of this AdresVoorkomenInOnderzoek.


        :param adresseerbaar_object_identificatie: The adresseerbaar_object_identificatie of this AdresVoorkomenInOnderzoek.
        :type adresseerbaar_object_identificatie: bool
        """

        self._adresseerbaar_object_identificatie = adresseerbaar_object_identificatie

    @property
    def functie_adres(self) -> bool:
        """Gets the functie_adres of this AdresVoorkomenInOnderzoek.


        :return: The functie_adres of this AdresVoorkomenInOnderzoek.
        :rtype: bool
        """
        return self._functie_adres

    @functie_adres.setter
    def functie_adres(self, functie_adres: bool):
        """Sets the functie_adres of this AdresVoorkomenInOnderzoek.


        :param functie_adres: The functie_adres of this AdresVoorkomenInOnderzoek.
        :type functie_adres: bool
        """

        self._functie_adres = functie_adres
