from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from brp.historie_api.models.base_model import Model
import re
from brp.historie_api import util

import re  # noqa: E501

class HistorieQuery(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, burgerservicenummer=None):  # noqa: E501
        """HistorieQuery - a model defined in OpenAPI

        :param type: The type of this HistorieQuery.  # noqa: E501
        :type type: str
        :param burgerservicenummer: The burgerservicenummer of this HistorieQuery.  # noqa: E501
        :type burgerservicenummer: str
        """
        self.openapi_types = {
            'type': str,
            'burgerservicenummer': str
        }

        self.attribute_map = {
            'type': 'type',
            'burgerservicenummer': 'burgerservicenummer'
        }

        self._type = type
        self._burgerservicenummer = burgerservicenummer

    @classmethod
    def from_dict(cls, dikt) -> 'HistorieQuery':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The HistorieQuery of this HistorieQuery.  # noqa: E501
        :rtype: HistorieQuery
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this HistorieQuery.


        :return: The type of this HistorieQuery.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this HistorieQuery.


        :param type: The type of this HistorieQuery.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def burgerservicenummer(self) -> str:
        """Gets the burgerservicenummer of this HistorieQuery.


        :return: The burgerservicenummer of this HistorieQuery.
        :rtype: str
        """
        return self._burgerservicenummer

    @burgerservicenummer.setter
    def burgerservicenummer(self, burgerservicenummer: str):
        """Sets the burgerservicenummer of this HistorieQuery.


        :param burgerservicenummer: The burgerservicenummer of this HistorieQuery.
        :type burgerservicenummer: str
        """
        if burgerservicenummer is None:
            raise ValueError("Invalid value for `burgerservicenummer`, must not be `None`")  # noqa: E501
        if burgerservicenummer is not None and not re.search(r'^[0-9]{9}$', burgerservicenummer):  # noqa: E501
            raise ValueError(r"Invalid value for `burgerservicenummer`, must be a follow pattern or equal to `/^[0-9]{9}$/`")  # noqa: E501

        self._burgerservicenummer = burgerservicenummer
