from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from brp.historie_api.models.base_model import Model
from brp.historie_api.models.abstract_datum import AbstractDatum
from brp.historie_api import util

from brp.historie_api.models.abstract_datum import AbstractDatum  # noqa: E501

class LocatieVoorkomenInOnderzoek(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, datum_ingang_onderzoek=None, type=None, gemeente_van_inschrijving=None, datum_van=None, datum_tot=None, functie_adres=None):  # noqa: E501
        """LocatieVoorkomenInOnderzoek - a model defined in OpenAPI

        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this LocatieVoorkomenInOnderzoek.  # noqa: E501
        :type datum_ingang_onderzoek: AbstractDatum
        :param type: The type of this LocatieVoorkomenInOnderzoek.  # noqa: E501
        :type type: bool
        :param gemeente_van_inschrijving: The gemeente_van_inschrijving of this LocatieVoorkomenInOnderzoek.  # noqa: E501
        :type gemeente_van_inschrijving: bool
        :param datum_van: The datum_van of this LocatieVoorkomenInOnderzoek.  # noqa: E501
        :type datum_van: bool
        :param datum_tot: The datum_tot of this LocatieVoorkomenInOnderzoek.  # noqa: E501
        :type datum_tot: bool
        :param functie_adres: The functie_adres of this LocatieVoorkomenInOnderzoek.  # noqa: E501
        :type functie_adres: bool
        """
        self.openapi_types = {
            'datum_ingang_onderzoek': AbstractDatum,
            'type': bool,
            'gemeente_van_inschrijving': bool,
            'datum_van': bool,
            'datum_tot': bool,
            'functie_adres': bool
        }

        self.attribute_map = {
            'datum_ingang_onderzoek': 'datumIngangOnderzoek',
            'type': 'type',
            'gemeente_van_inschrijving': 'gemeenteVanInschrijving',
            'datum_van': 'datumVan',
            'datum_tot': 'datumTot',
            'functie_adres': 'functieAdres'
        }

        self._datum_ingang_onderzoek = datum_ingang_onderzoek
        self._type = type
        self._gemeente_van_inschrijving = gemeente_van_inschrijving
        self._datum_van = datum_van
        self._datum_tot = datum_tot
        self._functie_adres = functie_adres

    @classmethod
    def from_dict(cls, dikt) -> 'LocatieVoorkomenInOnderzoek':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The LocatieVoorkomenInOnderzoek of this LocatieVoorkomenInOnderzoek.  # noqa: E501
        :rtype: LocatieVoorkomenInOnderzoek
        """
        return util.deserialize_model(dikt, cls)

    @property
    def datum_ingang_onderzoek(self) -> AbstractDatum:
        """Gets the datum_ingang_onderzoek of this LocatieVoorkomenInOnderzoek.


        :return: The datum_ingang_onderzoek of this LocatieVoorkomenInOnderzoek.
        :rtype: AbstractDatum
        """
        return self._datum_ingang_onderzoek

    @datum_ingang_onderzoek.setter
    def datum_ingang_onderzoek(self, datum_ingang_onderzoek: AbstractDatum):
        """Sets the datum_ingang_onderzoek of this LocatieVoorkomenInOnderzoek.


        :param datum_ingang_onderzoek: The datum_ingang_onderzoek of this LocatieVoorkomenInOnderzoek.
        :type datum_ingang_onderzoek: AbstractDatum
        """

        self._datum_ingang_onderzoek = datum_ingang_onderzoek

    @property
    def type(self) -> bool:
        """Gets the type of this LocatieVoorkomenInOnderzoek.


        :return: The type of this LocatieVoorkomenInOnderzoek.
        :rtype: bool
        """
        return self._type

    @type.setter
    def type(self, type: bool):
        """Sets the type of this LocatieVoorkomenInOnderzoek.


        :param type: The type of this LocatieVoorkomenInOnderzoek.
        :type type: bool
        """

        self._type = type

    @property
    def gemeente_van_inschrijving(self) -> bool:
        """Gets the gemeente_van_inschrijving of this LocatieVoorkomenInOnderzoek.


        :return: The gemeente_van_inschrijving of this LocatieVoorkomenInOnderzoek.
        :rtype: bool
        """
        return self._gemeente_van_inschrijving

    @gemeente_van_inschrijving.setter
    def gemeente_van_inschrijving(self, gemeente_van_inschrijving: bool):
        """Sets the gemeente_van_inschrijving of this LocatieVoorkomenInOnderzoek.


        :param gemeente_van_inschrijving: The gemeente_van_inschrijving of this LocatieVoorkomenInOnderzoek.
        :type gemeente_van_inschrijving: bool
        """

        self._gemeente_van_inschrijving = gemeente_van_inschrijving

    @property
    def datum_van(self) -> bool:
        """Gets the datum_van of this LocatieVoorkomenInOnderzoek.


        :return: The datum_van of this LocatieVoorkomenInOnderzoek.
        :rtype: bool
        """
        return self._datum_van

    @datum_van.setter
    def datum_van(self, datum_van: bool):
        """Sets the datum_van of this LocatieVoorkomenInOnderzoek.


        :param datum_van: The datum_van of this LocatieVoorkomenInOnderzoek.
        :type datum_van: bool
        """

        self._datum_van = datum_van

    @property
    def datum_tot(self) -> bool:
        """Gets the datum_tot of this LocatieVoorkomenInOnderzoek.


        :return: The datum_tot of this LocatieVoorkomenInOnderzoek.
        :rtype: bool
        """
        return self._datum_tot

    @datum_tot.setter
    def datum_tot(self, datum_tot: bool):
        """Sets the datum_tot of this LocatieVoorkomenInOnderzoek.


        :param datum_tot: The datum_tot of this LocatieVoorkomenInOnderzoek.
        :type datum_tot: bool
        """

        self._datum_tot = datum_tot

    @property
    def functie_adres(self) -> bool:
        """Gets the functie_adres of this LocatieVoorkomenInOnderzoek.


        :return: The functie_adres of this LocatieVoorkomenInOnderzoek.
        :rtype: bool
        """
        return self._functie_adres

    @functie_adres.setter
    def functie_adres(self, functie_adres: bool):
        """Sets the functie_adres of this LocatieVoorkomenInOnderzoek.


        :param functie_adres: The functie_adres of this LocatieVoorkomenInOnderzoek.
        :type functie_adres: bool
        """

        self._functie_adres = functie_adres
