from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from brp.historie_api.models.base_model import Model
from brp.historie_api.models.waardetabel import Waardetabel
from brp.historie_api import util

from brp.historie_api.models.waardetabel import Waardetabel  # noqa: E501

class OpschortingBijhoudingBasis(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, reden=None):  # noqa: E501
        """OpschortingBijhoudingBasis - a model defined in OpenAPI

        :param reden: The reden of this OpschortingBijhoudingBasis.  # noqa: E501
        :type reden: Waardetabel
        """
        self.openapi_types = {
            'reden': Waardetabel
        }

        self.attribute_map = {
            'reden': 'reden'
        }

        self._reden = reden

    @classmethod
    def from_dict(cls, dikt) -> 'OpschortingBijhoudingBasis':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OpschortingBijhoudingBasis of this OpschortingBijhoudingBasis.  # noqa: E501
        :rtype: OpschortingBijhoudingBasis
        """
        return util.deserialize_model(dikt, cls)

    @property
    def reden(self) -> Waardetabel:
        """Gets the reden of this OpschortingBijhoudingBasis.


        :return: The reden of this OpschortingBijhoudingBasis.
        :rtype: Waardetabel
        """
        return self._reden

    @reden.setter
    def reden(self, reden: Waardetabel):
        """Sets the reden of this OpschortingBijhoudingBasis.


        :param reden: The reden of this OpschortingBijhoudingBasis.
        :type reden: Waardetabel
        """

        self._reden = reden
