from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from brp.historie_api.models.base_model import Model
from brp.historie_api.models.abstract_datum import AbstractDatum
from brp.historie_api.models.abstract_verblijfplaats_voorkomen import AbstractVerblijfplaatsVoorkomen
from brp.historie_api.models.rni_deelnemer import RniDeelnemer
from brp.historie_api.models.verblijfplaats_onbekend_voorkomen_in_onderzoek import VerblijfplaatsOnbekendVoorkomenInOnderzoek
from brp.historie_api.models.waardetabel import Waardetabel
from brp.historie_api import util

from brp.historie_api.models.abstract_datum import AbstractDatum  # noqa: E501
from brp.historie_api.models.abstract_verblijfplaats_voorkomen import AbstractVerblijfplaatsVoorkomen  # noqa: E501
from brp.historie_api.models.rni_deelnemer import RniDeelnemer  # noqa: E501
from brp.historie_api.models.verblijfplaats_onbekend_voorkomen_in_onderzoek import VerblijfplaatsOnbekendVoorkomenInOnderzoek  # noqa: E501
from brp.historie_api.models.waardetabel import Waardetabel  # noqa: E501

class VerblijfplaatsOnbekendVoorkomen(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, type=None, datum_van=None, datum_tot=None, gemeente_van_inschrijving=None, in_onderzoek=None, rni=None):  # noqa: E501
        """VerblijfplaatsOnbekendVoorkomen - a model defined in OpenAPI

        :param type: The type of this VerblijfplaatsOnbekendVoorkomen.  # noqa: E501
        :type type: str
        :param datum_van: The datum_van of this VerblijfplaatsOnbekendVoorkomen.  # noqa: E501
        :type datum_van: AbstractDatum
        :param datum_tot: The datum_tot of this VerblijfplaatsOnbekendVoorkomen.  # noqa: E501
        :type datum_tot: AbstractDatum
        :param gemeente_van_inschrijving: The gemeente_van_inschrijving of this VerblijfplaatsOnbekendVoorkomen.  # noqa: E501
        :type gemeente_van_inschrijving: Waardetabel
        :param in_onderzoek: The in_onderzoek of this VerblijfplaatsOnbekendVoorkomen.  # noqa: E501
        :type in_onderzoek: VerblijfplaatsOnbekendVoorkomenInOnderzoek
        :param rni: The rni of this VerblijfplaatsOnbekendVoorkomen.  # noqa: E501
        :type rni: RniDeelnemer
        """
        self.openapi_types = {
            'type': str,
            'datum_van': AbstractDatum,
            'datum_tot': AbstractDatum,
            'gemeente_van_inschrijving': Waardetabel,
            'in_onderzoek': VerblijfplaatsOnbekendVoorkomenInOnderzoek,
            'rni': RniDeelnemer
        }

        self.attribute_map = {
            'type': 'type',
            'datum_van': 'datumVan',
            'datum_tot': 'datumTot',
            'gemeente_van_inschrijving': 'gemeenteVanInschrijving',
            'in_onderzoek': 'inOnderzoek',
            'rni': 'rni'
        }

        self._type = type
        self._datum_van = datum_van
        self._datum_tot = datum_tot
        self._gemeente_van_inschrijving = gemeente_van_inschrijving
        self._in_onderzoek = in_onderzoek
        self._rni = rni

    @classmethod
    def from_dict(cls, dikt) -> 'VerblijfplaatsOnbekendVoorkomen':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VerblijfplaatsOnbekendVoorkomen of this VerblijfplaatsOnbekendVoorkomen.  # noqa: E501
        :rtype: VerblijfplaatsOnbekendVoorkomen
        """
        return util.deserialize_model(dikt, cls)

    @property
    def type(self) -> str:
        """Gets the type of this VerblijfplaatsOnbekendVoorkomen.


        :return: The type of this VerblijfplaatsOnbekendVoorkomen.
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type: str):
        """Sets the type of this VerblijfplaatsOnbekendVoorkomen.


        :param type: The type of this VerblijfplaatsOnbekendVoorkomen.
        :type type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    @property
    def datum_van(self) -> AbstractDatum:
        """Gets the datum_van of this VerblijfplaatsOnbekendVoorkomen.


        :return: The datum_van of this VerblijfplaatsOnbekendVoorkomen.
        :rtype: AbstractDatum
        """
        return self._datum_van

    @datum_van.setter
    def datum_van(self, datum_van: AbstractDatum):
        """Sets the datum_van of this VerblijfplaatsOnbekendVoorkomen.


        :param datum_van: The datum_van of this VerblijfplaatsOnbekendVoorkomen.
        :type datum_van: AbstractDatum
        """

        self._datum_van = datum_van

    @property
    def datum_tot(self) -> AbstractDatum:
        """Gets the datum_tot of this VerblijfplaatsOnbekendVoorkomen.


        :return: The datum_tot of this VerblijfplaatsOnbekendVoorkomen.
        :rtype: AbstractDatum
        """
        return self._datum_tot

    @datum_tot.setter
    def datum_tot(self, datum_tot: AbstractDatum):
        """Sets the datum_tot of this VerblijfplaatsOnbekendVoorkomen.


        :param datum_tot: The datum_tot of this VerblijfplaatsOnbekendVoorkomen.
        :type datum_tot: AbstractDatum
        """

        self._datum_tot = datum_tot

    @property
    def gemeente_van_inschrijving(self) -> Waardetabel:
        """Gets the gemeente_van_inschrijving of this VerblijfplaatsOnbekendVoorkomen.


        :return: The gemeente_van_inschrijving of this VerblijfplaatsOnbekendVoorkomen.
        :rtype: Waardetabel
        """
        return self._gemeente_van_inschrijving

    @gemeente_van_inschrijving.setter
    def gemeente_van_inschrijving(self, gemeente_van_inschrijving: Waardetabel):
        """Sets the gemeente_van_inschrijving of this VerblijfplaatsOnbekendVoorkomen.


        :param gemeente_van_inschrijving: The gemeente_van_inschrijving of this VerblijfplaatsOnbekendVoorkomen.
        :type gemeente_van_inschrijving: Waardetabel
        """

        self._gemeente_van_inschrijving = gemeente_van_inschrijving

    @property
    def in_onderzoek(self) -> VerblijfplaatsOnbekendVoorkomenInOnderzoek:
        """Gets the in_onderzoek of this VerblijfplaatsOnbekendVoorkomen.


        :return: The in_onderzoek of this VerblijfplaatsOnbekendVoorkomen.
        :rtype: VerblijfplaatsOnbekendVoorkomenInOnderzoek
        """
        return self._in_onderzoek

    @in_onderzoek.setter
    def in_onderzoek(self, in_onderzoek: VerblijfplaatsOnbekendVoorkomenInOnderzoek):
        """Sets the in_onderzoek of this VerblijfplaatsOnbekendVoorkomen.


        :param in_onderzoek: The in_onderzoek of this VerblijfplaatsOnbekendVoorkomen.
        :type in_onderzoek: VerblijfplaatsOnbekendVoorkomenInOnderzoek
        """

        self._in_onderzoek = in_onderzoek

    @property
    def rni(self) -> RniDeelnemer:
        """Gets the rni of this VerblijfplaatsOnbekendVoorkomen.


        :return: The rni of this VerblijfplaatsOnbekendVoorkomen.
        :rtype: RniDeelnemer
        """
        return self._rni

    @rni.setter
    def rni(self, rni: RniDeelnemer):
        """Sets the rni of this VerblijfplaatsOnbekendVoorkomen.


        :param rni: The rni of this VerblijfplaatsOnbekendVoorkomen.
        :type rni: RniDeelnemer
        """

        self._rni = rni
