from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from brp.historie_api.models.base_model import Model
from brp.historie_api.models.abstract_verblijfplaats_voorkomen import AbstractVerblijfplaatsVoorkomen
from brp.historie_api.models.opschorting_bijhouding import OpschortingBijhouding
from brp.historie_api import util

from brp.historie_api.models.abstract_verblijfplaats_voorkomen import AbstractVerblijfplaatsVoorkomen  # noqa: E501
from brp.historie_api.models.opschorting_bijhouding import OpschortingBijhouding  # noqa: E501

class VerblijfplaatshistorieQueryResponse(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, verblijfplaatsen=None, opschorting_bijhouding=None, geheimhouding_persoonsgegevens=None):  # noqa: E501
        """VerblijfplaatshistorieQueryResponse - a model defined in OpenAPI

        :param verblijfplaatsen: The verblijfplaatsen of this VerblijfplaatshistorieQueryResponse.  # noqa: E501
        :type verblijfplaatsen: List[AbstractVerblijfplaatsVoorkomen]
        :param opschorting_bijhouding: The opschorting_bijhouding of this VerblijfplaatshistorieQueryResponse.  # noqa: E501
        :type opschorting_bijhouding: OpschortingBijhouding
        :param geheimhouding_persoonsgegevens: The geheimhouding_persoonsgegevens of this VerblijfplaatshistorieQueryResponse.  # noqa: E501
        :type geheimhouding_persoonsgegevens: bool
        """
        self.openapi_types = {
            'verblijfplaatsen': List[AbstractVerblijfplaatsVoorkomen],
            'opschorting_bijhouding': OpschortingBijhouding,
            'geheimhouding_persoonsgegevens': bool
        }

        self.attribute_map = {
            'verblijfplaatsen': 'verblijfplaatsen',
            'opschorting_bijhouding': 'opschortingBijhouding',
            'geheimhouding_persoonsgegevens': 'geheimhoudingPersoonsgegevens'
        }

        self._verblijfplaatsen = verblijfplaatsen
        self._opschorting_bijhouding = opschorting_bijhouding
        self._geheimhouding_persoonsgegevens = geheimhouding_persoonsgegevens

    @classmethod
    def from_dict(cls, dikt) -> 'VerblijfplaatshistorieQueryResponse':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The VerblijfplaatshistorieQueryResponse of this VerblijfplaatshistorieQueryResponse.  # noqa: E501
        :rtype: VerblijfplaatshistorieQueryResponse
        """
        return util.deserialize_model(dikt, cls)

    @property
    def verblijfplaatsen(self) -> List[AbstractVerblijfplaatsVoorkomen]:
        """Gets the verblijfplaatsen of this VerblijfplaatshistorieQueryResponse.


        :return: The verblijfplaatsen of this VerblijfplaatshistorieQueryResponse.
        :rtype: List[AbstractVerblijfplaatsVoorkomen]
        """
        return self._verblijfplaatsen

    @verblijfplaatsen.setter
    def verblijfplaatsen(self, verblijfplaatsen: List[AbstractVerblijfplaatsVoorkomen]):
        """Sets the verblijfplaatsen of this VerblijfplaatshistorieQueryResponse.


        :param verblijfplaatsen: The verblijfplaatsen of this VerblijfplaatshistorieQueryResponse.
        :type verblijfplaatsen: List[AbstractVerblijfplaatsVoorkomen]
        """

        self._verblijfplaatsen = verblijfplaatsen

    @property
    def opschorting_bijhouding(self) -> OpschortingBijhouding:
        """Gets the opschorting_bijhouding of this VerblijfplaatshistorieQueryResponse.


        :return: The opschorting_bijhouding of this VerblijfplaatshistorieQueryResponse.
        :rtype: OpschortingBijhouding
        """
        return self._opschorting_bijhouding

    @opschorting_bijhouding.setter
    def opschorting_bijhouding(self, opschorting_bijhouding: OpschortingBijhouding):
        """Sets the opschorting_bijhouding of this VerblijfplaatshistorieQueryResponse.


        :param opschorting_bijhouding: The opschorting_bijhouding of this VerblijfplaatshistorieQueryResponse.
        :type opschorting_bijhouding: OpschortingBijhouding
        """

        self._opschorting_bijhouding = opschorting_bijhouding

    @property
    def geheimhouding_persoonsgegevens(self) -> bool:
        """Gets the geheimhouding_persoonsgegevens of this VerblijfplaatshistorieQueryResponse.

        Gegevens mogen niet worden verstrekt aan derden / maatschappelijke instellingen.   # noqa: E501

        :return: The geheimhouding_persoonsgegevens of this VerblijfplaatshistorieQueryResponse.
        :rtype: bool
        """
        return self._geheimhouding_persoonsgegevens

    @geheimhouding_persoonsgegevens.setter
    def geheimhouding_persoonsgegevens(self, geheimhouding_persoonsgegevens: bool):
        """Sets the geheimhouding_persoonsgegevens of this VerblijfplaatshistorieQueryResponse.

        Gegevens mogen niet worden verstrekt aan derden / maatschappelijke instellingen.   # noqa: E501

        :param geheimhouding_persoonsgegevens: The geheimhouding_persoonsgegevens of this VerblijfplaatshistorieQueryResponse.
        :type geheimhouding_persoonsgegevens: bool
        """

        self._geheimhouding_persoonsgegevens = geheimhouding_persoonsgegevens
